version: "3"

networks:
  laravel:
    driver: bridge

services:
  ####################################################################################################
  # PHP
  ####################################################################################################
  app:
    container_name: app
    build: .docker/php
    ports:
      - 5173:5173
    volumes:
      - ./src:/workspace:delegated
    networks:
      - laravel
    depends_on:
      - db
      - redis
      - mail

  ####################################################################################################
  # Nginx
  ####################################################################################################
  webserver:
    container_name: webserver
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/workspace:delegated
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - laravel

  ####################################################################################################
  # DATABASE (MySQL)
  ####################################################################################################
  #db:
  #  container_name: db
  #  image: mysql:8.1
  #  ports:
  #    - 3306:3306
  #  volumes:
  #    - .docker/db/data:/var/lib/mysql
  #    - .docker/logs:/var/log/mysql
  #    - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #    - .docker/db/sql:/docker-entrypoint-initdb.d
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_DATABASE: laravel_db_name
  #    MYSQL_USER: laravel_db_user
  #    MYSQL_PASSWORD: laravel_db_pass

  # ####################################################################################################
  # # DATABASE (MariaDB)
  # ####################################################################################################
  db:
    container_name: db
    image: mariadb:10.11
    ports:
      - 3306:3306
    volumes:
      - .docker/db/data:/var/lib/mysql
      - .docker/logs:/var/log/mysql
      - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_training
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - laravel

  # ####################################################################################################
  # # Redis
  # ####################################################################################################
  redis:
    container_name: redis
    image: redis:6.2.13-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - .docker/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - laravel

  # ####################################################################################################
  # # Redis Commander
  # ####################################################################################################
  redis-commander:
    container_name: redis_commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    links:
      - redis
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=root
    ports:
      - 6380:8081
    networks:
      - laravel

  # ####################################################################################################
  # # Mailpit
  # ####################################################################################################
  mail:
    container_name: mailserver
    image: axllent/mailpit:latest
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - laravel

  ####################################################################################################
  # Mailhog
  ####################################################################################################
  # mail:
  #   container_name: mailserver
  #   image: mailhog/mailhog:latest
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
  #   networks:
  #     - laravel

  ####################################################################################################
  # supervisor
  ####################################################################################################
  supervisor:
    container_name: supervisor
    build: .docker/supervisor
    environment:
      - SUPERVISOR_APP_ROOT=${SUPERVISOR_APP_ROOT}
      - SUPERVISOR_QUEUE_DRIVER=${SUPERVISOR_QUEUE_DRIVER}
      - SUPERVISOR_QUEUE_OPTIONS=${SUPERVISOR_QUEUE_OPTIONS}
      - SUPERVISOR_USER=${SUPERVISOR_USER}
      - SUPERVISOR_NUM_PROCS=${SUPERVISOR_NUM_PROCS}
    depends_on:
      - app
      - redis
    volumes:
      - ./src:/workspace:delegated
    networks:
      - laravel
